### ISSUE TITLE
Arena enemy 123 replace name Issue

### ISSUE THREAD

**Issue by january19th** [Bodify/BetterBlizzPlates#1]
Hello Dear Developer.

Your work is mindblowing really appreciate it. But we have some issue about enemy 123 with replace enemy nickname. 

It is not working with these features
- Hide target highlight glow
- Use a sexy texture for nameplates

Best Regards

**Comment by Bodify** [comment]
Hello and thank you for the kind words!
That's odd I use these settings myself but definitely possible I've overlooked something.
I'm at work but I'll take a look when I get home.
Just so I've understood you correctly you're saying the Arena nameplates module that replaces name with id and/or spec is not working while you have "Hide target highlight glow" and "Use a sexy texture for nameplates" enabled?
Which mode are you using? And have you tried doing a /reload? It could be possible there are some wonky interraction with toggling certain features on and off while testing but might be solved with a /reload.

**Comment by Bodify** [comment]
I fatfingered Closed lol. Github learning curve right here.

**Comment by january19th** [comment]
Hahah! no problem. To be honest - replace name with Arena ID is completely not working. When I targeting enemy or friendly player, nicknames and arena numbers are overlapping. ( same problem on replace name with spec thing )

Also name size thing not working properly. Its just changing Vertical position of the names. I tried to reset cvar and other addons script etc. unfortunalty still could not solve these problems.

Note : My fonts are not blizzard classic fonts. Its FRIZQT__

**Comment by january19th** [comment]
I think i have to test your addon with different device. Because I have tons of custom script in my interface folder, checked every single thing but somehow something blocking your code functions. 

the good new is thats not related with custom fonts. 

Note: Dont forget it you are not only dev you are artist. This is the best thing ever and better than Plater addon because of no fps drop. 

Thank you so much for your precious time.

Regards.

Headshy - Doomhammer

**Comment by Bodify** [comment]
I see, that's good to know! Could be some other scripts messing it up yes.
Try testing enabling one addon/script after another and see if anything messes with it.
If you find the culprit please share and I'll see if there is anything I can do from my end, whether that be changing BetterBlizzPlates to accommodate the addon/script or help you out with making the addon/script work in unison with BetterBlizzPlates.
I'll leave this issue open for now and see if you get back to me with some info :)

**Comment by january19th** [comment]
Sad. I deleted whole game and  after reinstalled somehow still not working.  Name size thing only changing vertical position. Maybe it is dumb but that function only working good with NameplateColors addon.

**Comment by january19th** [comment]
local function SetFont(obj,optSize)
        local fontName=obj:GetFont();
        obj:SetFont(fontName,optSize,"THINOUTLINE");
    end
    
    SetFont(SystemFont_LargeNamePlate, 8)
    SetFont(SystemFont_NamePlate, 8)
    SetFont(SystemFont_LargeNamePlateFixed, 8)
    SetFont(SystemFont_NamePlateFixed, 8)
    
    
end

This is the script fixed everything. :) But Sexyfont thing crashing settings when I tick it.

**Comment by Bodify** [comment]
I'll be posting a bigger update tomorrow probably with some changes. I'm not sure if it will fix your problem but I have a hunch what the cause of the problem could be; I might have to change the way I do nameplate name size.

**Comment by Bodify** [comment]
Update is out. Let me know if your issue persists.

**Comment by january19th** [comment]
It is perfectly working. Thank you so much! Could you add nameplate height change option on next update? This is the code:

hooksecurefunc("DefaultCompactNamePlateFrameAnchorInternal", function(frame, setupOptions)
	setupOptions.healthBarHeight = 8 -- 4 Default
end)

**Comment by Bodify** [comment]
> hooksecurefunc("DefaultCompactNamePlateFrameAnchorInternal", function(frame, setupOptions) setupOptions.healthBarHeight = 8 -- 4 Default end)

I wasnt aware you could do that, neat! I'll add a slider for it in the next patch that should be out in a day or two I think.

**Comment by january19th** [comment]
Yeah.. I feel you. That's very complex. 2 years ago I found chinese nameplate addon. That was only one fixed that thing. It was also move entire nameplate anchor bottom and top. But I accidentally delete it and couldn't find again because addon language was full of chinese. 

I think addon called in Curseforge "nameplatecolors" will give you some ideas. Check the lua folder. 
Also, we have other small issue about the " casttimer next to castbar " option. I untick it but still timer reveals next to the castbar. 

If I find any solution I will be post here.

**Comment by Bodify** [comment]
> Also, we have other small issue about the " casttimer next to castbar " option. I untick it but still timer reveals next to the castbar.

I forgot an "if" statement. It's fixed in next update that's out real soon.

**Comment by january19th** [comment]
Oh. Thank you so much! Yeah it is working without any error. Turn your camera opposite side until nameplate closes for input refresh check. I set it up that script with auto login. When I login it is auto activated.

**Comment by january19th** [comment]
Greetings Sir, 

I just back this world and looks like your addon growing like a dragon.  

and I have some minimalistic ideas for other players to better visual compositions from other small addons. You know what, if we find true parts, we can change somethings in this game or real life. I would be very happy if you share with me your mail or discord ID.

Sincerely from Constantinople / Istanbul
