### ISSUE TITLE
Color threat in PvE

### ISSUE THREAD

**Issue by XimmortalAresX** [Bodify/BetterBlizzPlates#10]
Hey, when you have the "Color threat in PvE" option on it shows threat color on the personal resource display as well which is fairly pointless to see you have threat from your own nameplate, is it possible to exclude your own personal resource display from the threat color?

**Comment by Bodify** [comment]
Forgot about the github, oopsie. Someone else also reported this on CurseForge/Discord. Fixed in the version I'm working on rn probably out later today or tomorrow so I'll close this.
