### ISSUE TITLE
Permanent red glow for bleeds

### ISSUE THREAD

**Issue by Alezzzander** [Bodify/BetterBlizzPlates#12]
Hello,
Could you please guide me where i can set permanent red glow effect for bleeds/auras ? I found only pandemic aura,but its not permanent.Here is screenshot from some youtube video.
![изображение](https://github.com/user-attachments/assets/3f143bac-d2c5-4cf1-9ce8-8286f1579378)

**Comment by Bodify** [comment]
Hey this is for bug reports not questions. Head over to the discord channel or CurseForge for questions. With that said the setting is in /bbf -> Buffs & Debuffs and you add spells to the whitelist and check the Important Glow checkbox on them. Make sure youve also enabled the settings on Target & FocusFrame on the settings beneath.
