### ISSUE TITLE
Feature request: mouseover indicator

### ISSUE THREAD

**Issue by wouter-intveld** [Bodify/BetterBlizzPlates#14]
Hey, love the add-on <3. 

I would like to request a mouseover indicator when hovering over a nameplate. Something like a border or something similar.

Thanks :-)

**Comment by Bodify** [comment]
It's been requested a few times before but I haven't had inspiration to create it yet. I don't think theres a one size fits all solution here but I'm also not sure what to even do if I'm being honest.
If you have any examples of something let me know and I'll see what I can do in a future update.

**Comment by wouter-intveld** [comment]
No worries, I come from [KuiNameplates](https://www.curseforge.com/wow/addons/kuinameplates), which I used for several years. They have an option that allows for recoloring of the nameplate border on mouseover. I found it very useful in m+.

**Comment by nerolite** [comment]
I've been using[ Target Nameplate Indicator](https://www.curseforge.com/wow/addons/targetnameplateindicator) for this sole purpose of having a mouseover indicator. The rest is handled by BetterBlizzPlates (target/focus indicators.

It allows one to specify a texture, it's size, placement and opacity. These settings help to ensure I can make it stand out. 

Additionally, you can have different settings for whether the mouseover target is Self, Friendly or Hostile. I only use it for Hostile, but I reckon healers would benefit from having a different indicator for Friendly targets.

I can live with using two addons, but would transition if mouseover ever were to be introduced in BetterBlizzPlates.

**Comment by Bodify** [comment]
I actually added mouseover in the last patch but its very subtle and a bit buggy in the current version. You can find it in Misc. I might expand on it in the future but for now this subtle mouseover highlight will do. I have improved it in this new patch that I am working on that should be out later today or tomorrow. Closing this now but good suggestion @nerolite for the people wanting something a bit more advanced than what I offer in BBP.

**Comment by nerolite** [comment]
Excited to try it out. Thank you!
