### ISSUE TITLE
Bug: Cast bar spell name doesn't shrink to fit and is ellipsized

### ISSUE THREAD

**Issue by fearkite** [Bodify/BetterBlizzPlates#15]
As per title, the cast bar spell name doesn't shrink to fit and is ellipsized when the 'Enable cast bar customization' is  turned on. It also appears as huge text.

**Comment by Bodify** [comment]
Could you provide a screenshot example?

**Comment by fearkite** [comment]
![Screenshot 2024-09-08 145449](https://github.com/user-attachments/assets/3f1adfee-4a87-4b66-a545-15b348002c66)

Here is my settings currently applied:

![Screenshot 2024-09-08 145549](https://github.com/user-attachments/assets/868b2259-9db8-4531-9171-78ea21e123d3)
![Screenshot 2024-09-08 145546](https://github.com/user-attachments/assets/27489eb5-935a-44c4-af69-292382e55251)
![Screenshot 2024-09-08 145539](https://github.com/user-attachments/assets/da93ef50-3de1-44bd-9f73-e6471e22e05e)

**Comment by Bodify** [comment]
Thank you for getting back to me with screenshots. I've tried to keep things simple by making it so if the nameplate font gets changed all elements on the nameplate gets changed to that font. It seems some fonts are much larger than others causing this issue. But there are size settings for this in castbar section and for execute indicator in advanced settings. The nameplate target text and timer is missing these options but will get expanded on not too far away. Please try adjusting these settings to fit your font choice and let me know how it goes.

**Comment by fearkite** [comment]
Thanks for that tip! Not sure how I overlooked that setting. :D

Yes, adjusting the target text or having an option to put it inside the cast bar itself would be awesome, kinda like plater.

Thanks heaps the addon, it's lightweight and awesome!

**Comment by Bodify** [comment]
I will be adding more customization for it, yes, but it might not be in this upcoming patch. It will likely be in the next one, but it is coming.

I'll close this now.

Cheers,
Body
