### ISSUE TITLE
Feature request: Adjustable 'pandemic' timer

### ISSUE THREAD

**Issue by fearkite** [Bodify/BetterBlizzPlates#19]
Hey again mate! Loving this addon a lot. :D

I'd be in love with an adjustable pandemic timer or something to glow when a debuff is under a certain time, as playing a Warlock with [this](https://www.wowhead.com/spell=459376/perpetual-unstability) or [this](https://www.wowhead.com/spell=453034/volatile-agony) will feel amazing if notified accordingly.

Thanks again mate, appreciate you hard work. It does not go unnoticed!

**Comment by Bodify** [comment]
I don't think I'll make it customizeable, at least not for awhile. But I have added an exception for these two dots when those talents are learned in the upcoming version in a few days. Closing this now.
