### ISSUE TITLE
Request: Only show/glow purgeable if you can actually purge it

### ISSUE THREAD

**Issue by clicketz** [Bodify/BetterBlizzPlates#27]
If I'm on my druid I only want to see/glow enrage buffs so I can soothe them, I don't need to see all the magic buffs that I can't do anything about. A `Always show magic dispellable` checkbox might make sense to include all magic effects with

```Lua
or (aura.dispelName == "Magic" and aura.isHelpful)
``` 

but having `isPurgeable` default to

```Lua
aura.isStealable
```
alone makes more sense I think.

**Comment by Bodify** [comment]
Heyo! This was a bit of a quickie change I made. I agree that by default it should act that way. And there should be a setting to always show it. I have it like this in my other addon BetterBlizzFrames but I did a quickie here. Will fix it up when I get some time and add it as an optional setting.

**Comment by clicketz** [comment]
With the most recent changes, the buffs are still being displayed (just not glowing). If I'm on a druid I don't need to see that the target has a magic purgeable buff at all, imo. It should be filtered out completely (not just the glow).
