### ISSUE TITLE
[BUG] Erroring when approaching an interactable item

### ISSUE THREAD

**Issue by NoobTaco** [Bodify/BetterBlizzPlates#30]
When approaching an interactable object like a quest object or herb/ore node the addon is throwing an error.

```
8x integer overflow attempting to store -nan(ind)
[string "=[C]"]: in function `format'
[string "@BetterBlizzPlates/modules/execute.lua"]:140: in function `ExecuteIndicator'
[string "@BetterBlizzPlates/BetterBlizzPlates.lua"]:4256: in function <...rfaceBetterBlizzPlates/BetterBlizzPlates.lua:4100>
[string "@BetterBlizzPlates/BetterBlizzPlates.lua"]:4351: in function <...rfaceBetterBlizzPlates/BetterBlizzPlates.lua:4350>

Locals:
(*temporary) = "%d"
(*temporary) = Infinite
```

Addon Version: 1.6.7

**Comment by Bodify** [comment]
Thank you for the report will have a look. Would you mind sharing your soft target settings for these interactable objects? I don't use them myself and am a bit unsure how it all works. If not thats ok and I will look into that as well when I got some time.

**Comment by Bodify** [comment]
Hopefully fixed this in new update out either later today or tomorrow so closing this. I could not test it but I've changed some stuff so will hopefully work if not please re-open and get back to me how to test it.

**Comment by NoobTaco** [comment]
That did do the trick. No more error when mousing over a node!

Great work and thank you!! @Bodify
