### ISSUE TITLE
Error while testing nameplate auras

### ISSUE THREAD

**Issue by Gennoken** [Bodify/BetterBlizzPlates#33]
```
5x BetterBlizzPlates/modules/auras.lua:894: attempt to index local 'debuffColors' (a nil value)
[string "@BetterBlizzPlates/modules/auras.lua"]:894: in function <BetterBlizzPlates/modules/auras.lua:886>
```
this occur when clickting "test" in the nameplates auras section, and keeps occurring while test is enabled

**Comment by Bodify** [comment]
Thank you, I'll get this fixed for next version.

**Comment by Bodify** [comment]
Fixed this in new update out either later today or tomorrow so closing this.
