### ISSUE TITLE
Neurtal NPC Names

### ISSUE THREAD

**Issue by Gennoken** [Bodify/BetterBlizzPlates#34]
Hey, 
Unless i'm missing something or it's probably after last update, Neurtal NPC Names are not shown unless i target them.

Is this intended or i'm missing out some settings ?
Thank you

**Comment by Bodify** [comment]
I don't have settings for that in the addon, that behaviour comes from the default wow names settings. If you search for names in the blizzard settings youll find  "NPC Names". Set this to all NPCs. You can use AdvancedInterfaceOptions to search cvars and manage them individually and have more control etc.

As to why this has happened I think its just a coincidence on the update. Maybe you logged on alt that didnt have that cvar set or reset ur cvars or something? Idk. Let me know if you still have issues after.

**Comment by Gennoken** [comment]
Thank you for your reply,
In fact, changing to all NPCs in WoW interface show them all, but the problem is that i see now all friendly NPCs too even if their NP is hidden.

Before, i was using Plater, and even with NPC Names set to Hostile, Quests and Interactives i could see all enemy names regardless of their reaction.

I set  all NPCs for the time being till i find a better solution, this reply is just to let you know the details

**Comment by Bodify** [comment]
Hey. The better solution is like I mentioned:
> You can use AdvancedInterfaceOptions to search cvars and manage them individually and have more control etc.
The cvars are called UnitName and you can change all of them individually.

**Comment by Gennoken** [comment]
There is no need for CVars, changings to show All NPCs in interface options actually changes THAT particular CVar, the same thing

**Comment by Bodify** [comment]
I dont think you understand. The setting in the interface options toggles a bunch of cvars. Not just one, many. You have 0 control. If you get AdvancedInterfaceOptions it lets you control each individual setting instead of this default interface setting that toggles a bunch of things you dont have control over. Closing this now.
