### ISSUE TITLE
Nameplate Aura Glows not working

### ISSUE THREAD

**Issue by CobusE** [Bodify/BetterBlizzPlates#4]
The following I have noticed:

"Glow on purgeable buffs" does not add any glow
"Blue border on buffs" does not add any border
"Pandemic Glow" does not add any glow

"Important Glow" does work

I'm not sure what more information you need, just let me know and I can provide.
Might be useful to know I'm using Masque and ElvUI (with nameplates turned off) which could have some effect on overriding how you display buffs/debuffs.

I would also recommend a "test' feature for buffs so it would be easier to spot these issues, at the moment it's not so simple to test whether buffs are showing correctly (unless I'm missing something.

**Comment by Bodify** [comment]
Hello! Thank you for bringing this to my attention. There was some missing checks that made the textures parented to the wrong thing and therefor not showing. I have fixed them all now and the addon will be updated in a day or two.

I will also do my best to make a test feature. It might not be optimal at first but I'll give it a shot.

**Comment by CobusE** [comment]
Great! I look forward to testing it out!

**Comment by CobusE** [comment]
@Bodify just a note that I have updated to v1.4.3 and the Pandemic Glow does not work, the test mode is great though!
Waiting for an arena to pop to test whether the purgeable and blue border work

**Comment by Bodify** [comment]
Oh whoops. Thank you for the headsup. I saw the same mistake on all 3 and when blue border and purgeglow worked I just figured it was the same case for pandemic without testing. I'll have a deeper look into it, it's probably just a typo of sorts from back when I changed some stuff. I'll have it fixed soon enough.

**Comment by Bodify** [comment]
I've only spotted a potential flaw but I have never made it actually not work for me. Are you sure it doesn't work? Have you checked for any errors? Is there a specific aura you're testing with or does it not work on any? More info please :x

**Comment by Bodify** [comment]
They all work for me. You're positive you're not getting any errors?

**Comment by CobusE** [comment]
@Bodify is there a way to see errors that I don't know about? Nothing is popping up, but part of my UI might be hiding it.

In any case it's not a major thing so I wouldn't worry too much about it

**Comment by Bodify** [comment]
Get BugGrabber and BugSack addons, theyre used to fetch errors without being annoying. Allows for easy copypaste of the error as well.

**Comment by Bodify** [comment]
Potentially also upload your settings, stored in a file called BetterBlizzPlates.lua here: C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\_YOUR_ACCOUNT_NAME_HERE_\SavedVariables

That way I can test with your settings directly see if I find anything weird.

**Comment by CobusE** [comment]
@Bodify i just noticed something odd, when another SP puts VT on my target the pandemic glow works, but not my own. 
BugSack not reporting any errors, but will upload my saved variables in a bit

**Comment by Bodify** [comment]
> @Bodify i just noticed something odd, when another SP puts VT on my target the pandemic glow works, but not my own. BugSack not reporting any errors, but will upload my saved variables in a bit

Pandemic does currently not distinguish between others auras and yours. I need to add more settings for the nameplate auras. But it's weird it doesn't add to your own but to the other one, it's not an area I've got to test though so could very well be there's an issue there.

**Comment by Bodify** [comment]
You're 100% sure the spell ID for your vamp touch etc isnt different either? You might have some different talents that the other spriest and I have that changes the spell ID. Try to use name and see if that works.
