### ISSUE TITLE
Arena Nameplates shortened specc wrong

### ISSUE THREAD

**Issue by Nocturnethy** [Bodify/BetterBlizzPlates#5]
I use the FrameSort addon to sort the enemy Healer always on "Arena 1".
Sometimes the shortened specc is wrong. Example is attached. Here one can see that the Holy-Priest is UNHOLY and the UH-DK is HOLY.

![2024-03-07 12_29_04-](https://github.com/Bodify/BetterBlizzPlates/assets/119591552/40c10956-6a87-4d2a-9886-fa818c1292ec)

**Comment by Bodify** [comment]
Hey! Thanks for the report. It's a bit hard to tell with your UI but I think you're using mode number 3 right? Or is it mode number 4?
I'll look into it once I get some time and get it fixed.

**Comment by Bodify** [comment]
I took a quick peek and I see the error immediately. Forgot to update some logic when I added the FrameSort support. Pretty quick fix once I get to it.

**Comment by Bodify** [comment]
I meant in BBP, which Arena Nameplate mode you're using.  I thought the mistake was obvious but it was just the fallback class value being wrong as well so I'll have to fix that.

I got too curious so I had to look a bit but I don't have time rn unfortunately. I'll take a deeper look some other time and hopefully figure out whats wrong.

**Comment by Nocturnethy** [comment]
Alright so I dont have to provide you the BBP setting. But I will have a look neverthless and report it back.

So until youre able to fix it I will change the setting because it's really very annoying. Especially when there are two different speccs of the same class which arent a healer. For example a enhancement and a elemental shaman in the opposite team.

**Comment by Bodify** [comment]
Understandable.

Do you have a video clip?
How often are we talking?
Does hiding UI/Nameplates and showing it again fix it? 
Many unknowns here.
Especially weird is it that the priests' name is Unholy in the DK color but the DK's name is Holy but NOT in the priest color.

**Comment by Bodify** [comment]
Oh nevermind I just noticed the arms warrior is also red, so youre not using class colors. That clears up a bit of headache hah.

**Comment by Nocturnethy** [comment]
I record my games with wowarenalogs. So I can provide you a (few) Videos. Interesting is that the misbehaviour is not constant. Even within the same lobby it is not happening in every combo variarion

**Comment by Bodify** [comment]
Yeah even seeing it happen once would be great help, would also be interesting to see if it fixes itself or not later during the game.

**Comment by Nocturnethy** [comment]
Okay, I will upload two Videos on my cloud and link it for you here. In about 2 hours. Thanks for your fantastic work!

**Comment by Nocturnethy** [comment]
Here is a folder with videos where you can see how it's looking:
[https://drive.proton.me/urls/5BNANFPTDM#tGiwV6RJriPl](https://drive.proton.me/urls/5BNANFPTDM#tGiwV6RJriPl)

Also my settings in BBP:
![2024-03-07 22_52_44-World of Warcraft](https://github.com/Bodify/BetterBlizzPlates/assets/119591552/c1fc2f74-dbe2-48a5-944c-f033f3f3912d)

**Comment by Bodify** [comment]
Thank you, this is great footage.
I'm curious about your FrameSort settings as well, could you show me the main page of FrameSort and also the Sorting Method you use?

**Comment by Nocturnethy** [comment]
![2024-03-07 23_14_15-World of Warcraft](https://github.com/Bodify/BetterBlizzPlates/assets/119591552/7a1cc7b3-8d56-478d-b480-a8d0c53719c2)
![2024-03-07 23_14_31-World of Warcraft](https://github.com/Bodify/BetterBlizzPlates/assets/119591552/e7a521a4-5a32-4d55-8267-e44894ef7a5d)
![2024-03-07 23_14_40-World of Warcraft](https://github.com/Bodify/BetterBlizzPlates/assets/119591552/4fb346a6-07ef-4c0c-86d8-ebabe1c99440)

**Comment by Bodify** [comment]
I've identified the cause I think. Will fix it up and give it some testing during this weekend and should hopefully be good to go sometime this weekend as well.

**Comment by Nocturnethy** [comment]
Very cool, thank you! :D

**Comment by Bodify** [comment]
Allright things should be good now. Let me know if anything else pops up!
