### ISSUE TITLE
Getting the following error when targeting mobs

### ISSUE THREAD

**Issue by dabadoo** [Bodify/BetterBlizzPlates#9]
1434x ...rfaceBetterBlizzPlates/modules/classIcon.lua:297: attempt to index field 'classIndicator' (a nil value)
[string "@BetterBlizzPlates/modules/classIcon.lua"]:297: in function `ClassIndicatorTargetHighlight'
[string "@BetterBlizzPlates/modules/target.lua"]:551: in function <BetterBlizzPlates/modules/target.lua:465>

Locals:
frame = Button {
 0 = <userdata>
 debuffs = <table> {
 }
 WidgetContainer = Frame {
 }
 healPredictionDirty = false
 classificationIndicator = Texture {
 }
 hideCastbarOverride = false
 BigDebuffs = NamePlate1.BigDebuffs {
 }
 castBar = StatusBar {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 hideCastInfo = false
 displayedUnit = "nameplate1"
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = false
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 PlayerLevelDiffFrame = Frame {
 }
 ignoreCUFNameRequirement = true
 newUnit = true
 selectionHighlight = Texture {
 }
 ClassificationFrame = Frame {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate1"
 unitExists = true
 buffs = <table> {
 }
 disableMouse = true
 BetterBlizzPlates = <table> {
 }
 hideNameOverride = false
 questIndicator = Texture {
 }
 RaidTargetFrame = Frame {
 }
 dispels = <table> {
 }
 LoseAggroAnim = AnimationGroup {
 }
 BuffFrame = Frame {
 }
 murlocMode = Texture {
 }
 totalAbsorbOverlay = Texture {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 hideHealthBarMask = 0
 isLootObject = false
 healthBar = StatusBar {
 }
}
config = <table> {
 classIconColorBorder = true
 classIndicatorFriendlyScale = 1
 useCustomTextureForEnemy = false
 customTextureInitialized = true
 nameplateAuraPlayersOnlyShowTarget = false
 raidmarkIndicator = false
 customTextureSelfMana = "Interface\Buttons\WHITE8X8"
 classIndicatorHideRaidMarker = true
 auraColor = false
 classIndicatorHighlight = true
 classIconArenaOnly = false
 updateNameInitialized = true
 classIndicatorSpecIcon = false
 enemyHealthBarColor = false
 totemIndicator = true
 totemIndicatorColorName = true
 enableNameplateAuraCustomisation = false
 customTextureFriendly = "Interface\Addons\BetterBlizzPlates\media\DragonflightTexture"
 useCustomTextureForSelfMana = false
 arenaIndicators = true
 partyPointer = true
 totemIndicatorTestMode = false
 friendlyHideHealthBarNpc = true
 totemIndicatorTest = false
 hideResourceOnFriend = false
 showTotemIndicatorCooldownSwipe = true
 colorNPC = false
 totemIndicatorHideHealthBar = false
 classIndicatorAnchor = "TOP"
 targetIndicatorColorNameplate = false
 classIndicatorHighlightColor = true
 colorTargetName = false
 classIndicatorFriendlyAnchor = "TOP"
 questIndicator = true
 useCustomTextureForExtraBars = false
 hideNpcMurlocYPos = 0
 showGuildNames = false
 classIconSquareBorder = false
 hideTargetHighlight = false
 friendlyHealthBarColor = false
 targetIndicator = false
 enemyNeutralHealthBarColorRGB = <table> {
 }
 classIndicatorEnemy = false
 petIndicator = false
 changeNameplateBorderColor = false
 enemyHealthBarColorNpcOnly = false
 colorFocusName = false
 useCustomTextureForSelf = false
 healerIndicator = false
 useCustomTextureForFriendly = false
 useFakeName = false
 totemIndicatorInitialized = true
 colorNPCName = false
 updateHealthColorInitialized = true
 focusTargetIndicator = false
 targetIndicatorColorNameplateRGB = <table> {
 }
 fadeOutNPC = false
 hideFriendlyNameText = false
 totemIndicatorAnchor = "TOP"
 totemIndicatorYPos = 0
 nameplateResourceOnTarget = "0"
 friendlyHideHealthBar = true
 classIndicatorScale = 1
 useCustomTextureForBars = false
 hideEnemyNameText = false
 enemyHealthBarColorRGB = <table> {
 }
 classIconBgOnly = false
 anonModeOn = false
 changeNameplateBorderSize = false
 classColorPersonalNameplate = false
 friendIndicator = false
 castBarEmphasisHealthbarColor = false
 hideRaidmarkIndicator = false
 totemIndicatorColorHealthBar = true
 totemIndicatorDefaultCooldownTextSize = 0.850000
 changeHealthbarHeight = false
 totemIndicatorScale = 1
 totemIndicatorEnemyOnly = true
 totemIndicatorHideNameAndShiftIconDown = false
 classIndicatorFriendlyYPos = 0
 healthNumbers = false
 enableCastbarCustomization = false
 focusTargetIndicatorColorNameplateRGB = <table> {
 }
 totemIndicatorXPos = 0

**Comment by Bodify** [comment]
Forgot about the github. Fixed this loooong time ago. Sorry bout the late response.
